export type CoverageFlag = 'covered' | 'possible' | 'out_of_range'

export interface TownData {
  name: string
  slug: string
  coverage_flag: CoverageFlag
  contracts: number
  nearest_bn: string
  nearest_bn_distance_km: number
  centroid_lat: number
  centroid_lng: number
  avg_monthly_fee_rands: number
  avg_monthly_saving_rands: number
  campaigns: string[]
}

// 27 West Coast towns with ≥5 TRUSC contracts in CircleTel's target geography.
// Source: internal TRUSC billing dataset (1,470 contracts), geocoded April 2026.
// avg_monthly_fee_rands: median of sampled TRUSC contracts in town (outliers removed).
// avg_monthly_saving_rands: avg_monthly_fee_rands minus CircleTel entry price (R449).
export const TOWNS: TownData[] = [
  {
    name: 'Clanwilliam',
    slug: 'clanwilliam',
    coverage_flag: 'covered',
    contracts: 42,
    nearest_bn: 'Clanwilliam TV IHS',
    nearest_bn_distance_km: 1.5,
    centroid_lat: -32.18504,
    centroid_lng: 18.89306,
    avg_monthly_fee_rands: 543,
    avg_monthly_saving_rands: 94,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Malmesbury',
    slug: 'malmesbury',
    coverage_flag: 'covered',
    contracts: 41,
    nearest_bn: 'Malmesbury Klipkoppie',
    nearest_bn_distance_km: 5.8,
    centroid_lat: -33.45947,
    centroid_lng: 18.72764,
    avg_monthly_fee_rands: 672,
    avg_monthly_saving_rands: 223,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Piketberg',
    slug: 'piketberg',
    coverage_flag: 'out_of_range',
    contracts: 36,
    nearest_bn: 'Moorreesburg Agrico',
    nearest_bn_distance_km: 29.1,
    centroid_lat: -32.9,
    centroid_lng: 18.76667,
    avg_monthly_fee_rands: 621,
    avg_monthly_saving_rands: 172,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Moorreesburg',
    slug: 'moorreesburg',
    coverage_flag: 'covered',
    contracts: 34,
    nearest_bn: 'Moorreesburg Agrico',
    nearest_bn_distance_km: 1.1,
    centroid_lat: -33.15,
    centroid_lng: 18.66667,
    avg_monthly_fee_rands: 401,
    avg_monthly_saving_rands: 0,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Vanrhynsdorp',
    slug: 'vanrhynsdorp',
    coverage_flag: 'out_of_range',
    contracts: 29,
    nearest_bn: 'Vredendal Secondary',
    nearest_bn_distance_km: 21.6,
    centroid_lat: -31.61667,
    centroid_lng: 18.73333,
    avg_monthly_fee_rands: 436,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Lambertsbaai',
    slug: 'lambertsbaai',
    coverage_flag: 'out_of_range',
    contracts: 25,
    nearest_bn: 'Vredendal Secondary',
    nearest_bn_distance_km: 25.0,
    centroid_lat: -32.05,
    centroid_lng: 18.3,
    avg_monthly_fee_rands: 532,
    avg_monthly_saving_rands: 83,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Nababeep',
    slug: 'nababeep',
    coverage_flag: 'possible',
    contracts: 24,
    nearest_bn: 'Springbok Mnet IHS',
    nearest_bn_distance_km: 12.3,
    centroid_lat: -29.6,
    centroid_lng: 17.76667,
    avg_monthly_fee_rands: 371,
    avg_monthly_saving_rands: 0,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Lutzville',
    slug: 'lutzville',
    coverage_flag: 'out_of_range',
    contracts: 24,
    nearest_bn: 'Vredendal Secondary',
    nearest_bn_distance_km: 18.0,
    centroid_lat: -31.55,
    centroid_lng: 18.35,
    avg_monthly_fee_rands: 468,
    avg_monthly_saving_rands: 19,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Klawer',
    slug: 'klawer',
    coverage_flag: 'out_of_range',
    contracts: 23,
    nearest_bn: 'Vredendal Secondary',
    nearest_bn_distance_km: 15.0,
    centroid_lat: -31.78333,
    centroid_lng: 18.61667,
    avg_monthly_fee_rands: 402,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Velddrif',
    slug: 'velddrif',
    coverage_flag: 'out_of_range',
    contracts: 21,
    nearest_bn: 'Saldanha Bay W Res',
    nearest_bn_distance_km: 28.0,
    centroid_lat: -32.77278,
    centroid_lng: 18.16667,
    avg_monthly_fee_rands: 383,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Vredendal',
    slug: 'vredendal',
    coverage_flag: 'covered',
    contracts: 21,
    nearest_bn: 'Vredendal Secondary',
    nearest_bn_distance_km: 0.6,
    centroid_lat: -31.67,
    centroid_lng: 18.5,
    avg_monthly_fee_rands: 413,
    avg_monthly_saving_rands: 0,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Okiep',
    slug: 'okiep',
    coverage_flag: 'covered',
    contracts: 19,
    nearest_bn: 'Springbok Mnet IHS',
    nearest_bn_distance_km: 7.0,
    centroid_lat: -29.65,
    centroid_lng: 17.88333,
    avg_monthly_fee_rands: 414,
    avg_monthly_saving_rands: 0,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Langebaan',
    slug: 'langebaan',
    coverage_flag: 'possible',
    contracts: 18,
    nearest_bn: 'Saldanha Bay W Res',
    nearest_bn_distance_km: 13.0,
    centroid_lat: -33.08333,
    centroid_lng: 18.03333,
    avg_monthly_fee_rands: 539,
    avg_monthly_saving_rands: 90,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Vredenburg',
    slug: 'vredenburg',
    coverage_flag: 'covered',
    contracts: 16,
    nearest_bn: 'Vredenburg W Tower',
    nearest_bn_distance_km: 1.4,
    centroid_lat: -32.9,
    centroid_lng: 17.98333,
    avg_monthly_fee_rands: 448,
    avg_monthly_saving_rands: 0,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Graafwater',
    slug: 'graafwater',
    coverage_flag: 'out_of_range',
    contracts: 14,
    nearest_bn: 'Clanwilliam TV IHS',
    nearest_bn_distance_km: 22.0,
    centroid_lat: -32.15,
    centroid_lng: 18.58333,
    avg_monthly_fee_rands: 553,
    avg_monthly_saving_rands: 104,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Citrusdal',
    slug: 'citrusdal',
    coverage_flag: 'out_of_range',
    contracts: 13,
    nearest_bn: 'Clanwilliam TV IHS',
    nearest_bn_distance_km: 28.0,
    centroid_lat: -32.58333,
    centroid_lng: 19.0,
    avg_monthly_fee_rands: 442,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Saron',
    slug: 'saron',
    coverage_flag: 'out_of_range',
    contracts: 11,
    nearest_bn: 'Moorreesburg Agrico',
    nearest_bn_distance_km: 20.0,
    centroid_lat: -33.18333,
    centroid_lng: 19.08333,
    avg_monthly_fee_rands: 420,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Darling',
    slug: 'darling',
    coverage_flag: 'out_of_range',
    contracts: 10,
    nearest_bn: 'Malmesbury Klipkoppie',
    nearest_bn_distance_km: 22.0,
    centroid_lat: -33.37778,
    centroid_lng: 18.38333,
    avg_monthly_fee_rands: 374,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Porterville',
    slug: 'porterville',
    coverage_flag: 'out_of_range',
    contracts: 7,
    nearest_bn: 'Moorreesburg Agrico',
    nearest_bn_distance_km: 25.0,
    centroid_lat: -33.0,
    centroid_lng: 19.0,
    avg_monthly_fee_rands: 337,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Springbok',
    slug: 'springbok',
    coverage_flag: 'covered',
    contracts: 6,
    nearest_bn: 'Springbok Mnet IHS',
    nearest_bn_distance_km: 2.0,
    centroid_lat: -29.66667,
    centroid_lng: 17.88333,
    avg_monthly_fee_rands: 437,
    avg_monthly_saving_rands: 0,
    campaigns: ['A — Tarana FWA'],
  },
  {
    name: 'Saldanha',
    slug: 'saldanha',
    coverage_flag: 'out_of_range',
    contracts: 5,
    nearest_bn: 'Saldanha Bay W Res',
    nearest_bn_distance_km: 3.0,
    centroid_lat: -33.01667,
    centroid_lng: 17.95,
    avg_monthly_fee_rands: 437,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Elandsbaai',
    slug: 'elandsbaai',
    coverage_flag: 'out_of_range',
    contracts: 5,
    nearest_bn: 'Vredendal Secondary',
    nearest_bn_distance_km: 30.0,
    centroid_lat: -32.3,
    centroid_lng: 18.33333,
    avg_monthly_fee_rands: 498,
    avg_monthly_saving_rands: 49,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Chatsworth',
    slug: 'chatsworth',
    coverage_flag: 'out_of_range',
    contracts: 5,
    nearest_bn: 'Moorreesburg Agrico',
    nearest_bn_distance_km: 18.0,
    centroid_lat: -33.3,
    centroid_lng: 18.9,
    avg_monthly_fee_rands: 486,
    avg_monthly_saving_rands: 37,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Aurora',
    slug: 'aurora',
    coverage_flag: 'out_of_range',
    contracts: 5,
    nearest_bn: 'Moorreesburg Agrico',
    nearest_bn_distance_km: 16.0,
    centroid_lat: -32.68333,
    centroid_lng: 18.48333,
    avg_monthly_fee_rands: 406,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Koringberg',
    slug: 'koringberg',
    coverage_flag: 'out_of_range',
    contracts: 5,
    nearest_bn: 'Moorreesburg Agrico',
    nearest_bn_distance_km: 14.0,
    centroid_lat: -33.0,
    centroid_lng: 18.65,
    avg_monthly_fee_rands: 370,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
  {
    name: 'Bergsig',
    slug: 'bergsig',
    coverage_flag: 'out_of_range',
    contracts: 5,
    nearest_bn: 'Springbok Mnet IHS',
    nearest_bn_distance_km: 15.0,
    centroid_lat: -29.55,
    centroid_lng: 17.9,
    avg_monthly_fee_rands: 330,
    avg_monthly_saving_rands: 0,
    campaigns: ['B — MTN LTE/5G'],
  },
]

export function getTownBySlug(slug: string): TownData | undefined {
  return TOWNS.find((t) => t.slug === slug)
}

export function getCoveredTowns(): TownData[] {
  return TOWNS.filter((t) => t.coverage_flag === 'covered' || t.coverage_flag === 'possible')
}
