
project_id = "agyjovdugmtopasyvlng"

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://agyjovdugmtopasyvlng.supabase.co/functions/v1/zoho-callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 600

[functions.zoho-crm]
verify_jwt = false

[functions.zoho-callback]
verify_jwt = false

[functions.check-fttb-coverage]
verify_jwt = false

[functions.unjani-form-submission]
verify_jwt = false

[functions.send-audit-notification]
verify_jwt = false

[functions.check-coverage]
verify_jwt = false

