import type { FiveGDealPackage } from '@/lib/products/five-g-deals';

export const fiveGListingPackages: FiveGDealPackage[] = [
  {
    id: 'con-035',
    sku: 'CC-5G-CON-035',
    slug: 'circleconnect-5g-35-mbps',
    name: 'CircleConnect 5G 35 Mbps',
    description: 'Uncapped 5G at 35 Mbps with a router on a 24-month contract.',
    service_type: '5G',
    speed_down: 35,
    speed_up: 10,
    price: 489,
    promotion_price: null,
    features: ['Uncapped data', 'Free router'],
    metadata: {
      router_included: true,
      router_model: 'Huawei 5G CPE',
      contract_type: '24-month-contract',
      contract_duration: '24 Months',
      data_cap: 'Uncapped (500GB FUP)',
      fup_limit_gb: 500,
    },
  },
  {
    id: 'm2m-035',
    sku: 'CC-5G-M2M-035',
    slug: 'circleconnect-5g-35-mbps-sim-only',
    name: 'CircleConnect 5G 35 Mbps SIM Only',
    description: 'Month-to-month SIM only.',
    service_type: '5G',
    speed_down: 35,
    speed_up: 10,
    price: 539,
    promotion_price: null,
    features: ['SIM only'],
    metadata: {
      router_included: false,
      contract_type: 'month-to-month',
      contract_duration: 'Month-to-Month',
      data_cap: '500GB FUP',
      fup_limit_gb: 500,
    },
  },
  {
    id: 'op-unc-20',
    sku: 'CC-OP-UNC-20',
    slug: 'circleconnect-uncapped-20-mbps',
    name: 'CircleConnect Uncapped 20 Mbps',
    description: 'Uncapped 20 Mbps with a Huawei H155-386 on a 24-month contract.',
    service_type: 'LTE',
    speed_down: 20,
    speed_up: 20,
    price: 599,
    promotion_price: 549,
    features: ['Uncapped data', 'Huawei H155-386 included'],
    metadata: {
      router_included: true,
      router_model: 'Huawei H155-386 5G CPE',
      contract_type: '24-month-contract',
      contract_duration: '24 Months',
      data_cap: 'Uncapped',
    },
  },
  {
    id: 'con-060',
    sku: 'CC-5G-CON-060',
    slug: 'circleconnect-5g-60-mbps',
    name: 'CircleConnect 5G 60 Mbps',
    description: 'Uncapped 5G 60 Mbps with a router on a 24-month contract.',
    service_type: '5G',
    speed_down: 60,
    speed_up: 20,
    price: 699,
    promotion_price: 649,
    features: ['Uncapped data', 'Free router'],
    metadata: {
      router_included: true,
      router_model: 'Tozed ZLT X100 Pro / Huawei H155-386',
      contract_type: '24-month-contract',
      contract_duration: '24 Months',
      data_cap: 'Uncapped (800GB FUP)',
      fup_limit_gb: 800,
    },
  },
  {
    id: 'm2m-fwa',
    sku: 'CC-5G-M2M-FWA',
    slug: 'circleconnect-5g-fwa-500-gb',
    name: 'CircleConnect 5G FWA 500 GB',
    description: '500 GB hard cap, SIM only.',
    service_type: '5G',
    speed_down: 0,
    speed_up: 0,
    price: 649,
    promotion_price: null,
    features: ['500 GB hard cap'],
    metadata: {
      router_included: false,
      contract_type: 'month-to-month',
      data_cap: '500GB hard cap',
      data_cap_gb: 500,
      capped: true,
    },
  },
  {
    id: 'm2m-060',
    sku: 'CC-5G-M2M-060',
    slug: 'circleconnect-5g-60-mbps-sim-only',
    name: 'CircleConnect 5G 60 Mbps SIM Only',
    description: 'Month-to-month SIM only.',
    service_type: '5G',
    speed_down: 60,
    speed_up: 20,
    price: 759,
    promotion_price: null,
    features: ['SIM only'],
    metadata: {
      router_included: false,
      contract_type: 'month-to-month',
      data_cap: '800GB FUP',
      fup_limit_gb: 800,
    },
  },
  {
    id: 'con-be',
    sku: 'CC-5G-CON-BE',
    slug: 'circleconnect-5g-best-effort',
    name: 'CircleConnect 5G Best Effort',
    description: 'Best Effort 5G with a router.',
    service_type: '5G',
    speed_down: 300,
    speed_up: 50,
    price: 1029,
    promotion_price: null,
    features: ['Best Effort speeds'],
    metadata: {
      router_included: true,
      router_model: 'Huawei 5G CPE',
      contract_type: '24-month-contract',
      data_cap: 'Uncapped (1.5TB FUP)',
      fup_limit_gb: 1500,
      typical_speed: '100-300 Mbps',
    },
  },
  {
    id: 'm2m-be',
    sku: 'CC-5G-M2M-BE',
    slug: 'circleconnect-5g-best-effort-sim-only',
    name: 'CircleConnect 5G Best Effort SIM Only',
    description: 'Best Effort SIM only.',
    service_type: '5G',
    speed_down: 300,
    speed_up: 50,
    price: 1079,
    promotion_price: null,
    features: ['SIM only'],
    metadata: {
      router_included: false,
      contract_type: 'month-to-month',
      data_cap: '1.5TB FUP',
      fup_limit_gb: 1500,
      typical_speed: '100-300 Mbps',
    },
  },
];

export const fiveG60Product = fiveGListingPackages.find((row) => row.sku === 'CC-5G-CON-060')!;
export const uncapped20Product = fiveGListingPackages.find((row) => row.sku === 'CC-OP-UNC-20')!;
export const fwa500Product = fiveGListingPackages.find((row) => row.sku === 'CC-5G-M2M-FWA')!;
export const bestEffortSimProduct = fiveGListingPackages.find((row) => row.sku === 'CC-5G-M2M-BE')!;
