// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  case_study: dynamic(() => import("./CaseStudy")),
  comparison_table: dynamic(() => import("./ComparisonTable")),
  faq: dynamic(() => import("./FAQ")),
  feature_grid: dynamic(() => import("./FeatureGrid")),
  hero_section: dynamic(() => import("./HeroSection")),
  pricing_table: dynamic(() => import("./PricingTable")),
  recipe: dynamic(() => import("./Recipe")),
};
