-- =============================================================================
-- ZOHO Billing Integration - Phase 1: Invoice Sync Fields
-- =============================================================================
-- Description: Add ZOHO Billing sync fields to customer_invoices table
-- Version: 1.0
-- Created: 2025-01-20
-- =============================================================================

-- Add ZOHO Billing fields to customer_invoices table
ALTER TABLE public.customer_invoices
  ADD COLUMN IF NOT EXISTS zoho_billing_invoice_id TEXT,
  ADD COLUMN IF NOT EXISTS zoho_sync_status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS zoho_last_synced_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS zoho_last_sync_error TEXT;

-- Add check constraint for sync status
ALTER TABLE public.customer_invoices
  ADD CONSTRAINT customer_invoices_zoho_sync_status_check
  CHECK (zoho_sync_status IS NULL OR zoho_sync_status IN (
    'pending', 'syncing', 'synced', 'failed', 'retrying'
  ));

-- Create index for ZOHO Invoice ID lookups (performance)
CREATE INDEX IF NOT EXISTS idx_customer_invoices_zoho_billing_invoice_id
  ON public.customer_invoices(zoho_billing_invoice_id)
  WHERE zoho_billing_invoice_id IS NOT NULL;

-- Create index for finding failed syncs
CREATE INDEX IF NOT EXISTS idx_customer_invoices_zoho_sync_status
  ON public.customer_invoices(zoho_sync_status)
  WHERE zoho_sync_status = 'failed';

-- Create composite index for invoices needing sync (exclude recurring - ZOHO generates those)
CREATE INDEX IF NOT EXISTS idx_customer_invoices_pending_sync
  ON public.customer_invoices(invoice_type, zoho_sync_status, created_at)
  WHERE zoho_sync_status = 'pending'
    AND invoice_type IN ('installation', 'pro_rata', 'equipment', 'adjustment');

-- Comments
COMMENT ON COLUMN public.customer_invoices.zoho_billing_invoice_id IS
'ZOHO Billing Invoice ID. Links CircleTel invoice to ZOHO. Note: Recurring invoices are auto-generated by ZOHO from subscriptions. Only sync installation, pro-rata, equipment, and adjustment invoices.';

COMMENT ON COLUMN public.customer_invoices.zoho_sync_status IS
'Invoice sync status: pending (not synced), syncing (in progress), synced (success), failed (permanent), retrying (temporary failure)';

COMMENT ON COLUMN public.customer_invoices.zoho_last_synced_at IS
'Timestamp of last successful sync to ZOHO Billing';

COMMENT ON COLUMN public.customer_invoices.zoho_last_sync_error IS
'Last error message if invoice sync failed. Contains API error details for troubleshooting.';

-- =============================================================================
-- Migration Complete
-- =============================================================================
-- Next: Run migration 20250120000013 for payment_transactions table
-- =============================================================================
