import { Product } from './types';

export const CATEGORIES = [
  "All Categories",
  "business_fibre",
  "business",
  "lte",
  "5g",
  "wireless",
  "fibre_consumer"
];

export const MOCK_PRODUCTS: Product[] = [
  // --- Business Fibre ---
  {
    id: '1',
    name: 'Test Fibre 50/50',
    sku: 'test-fbr-50-50',
    category: 'business_fibre',
    price: 799,
    currency: 'R',
    billingCycle: 'month',
    status: 'inactive',
    syncStatus: 'synced',
    description: 'Test 50/50 Mbps business fibre plan',
    tags: ['HomeFibreConnect'],
    specs: { download: '50Mbps', upload: '50Mbps', type: 'Fibre' },
    lastUpdated: '11/16/2025',
    isHidden: true,
  },
  // --- Business ---
  {
    id: '2',
    name: 'MTN Made For Business S',
    sku: '202501EBU8176',
    category: 'business',
    price: 159,
    currency: 'R',
    billingCycle: 'month',
    status: 'inactive',
    syncStatus: 'synced',
    description: 'Made For Business S - 1.5GB Data • 100 Minutes • 500 SMS • 24 Mo...',
    tags: ['5g'],
    specs: { dataLimit: '1.5GB', type: 'Mobile' },
    lastUpdated: '11/16/2025',
    isHidden: true,
  },
  {
    id: '3',
    name: 'MTN Made For Business M+ + Apple iPhone Air',
    sku: '202501EBU8516',
    category: 'business',
    price: 1199,
    currency: 'R',
    billingCycle: 'month',
    status: 'inactive',
    syncStatus: 'not_synced',
    description: 'Made For Business M+ • 6GB Data • 400 Minutes • 36 Month Contract',
    tags: ['5g', 'Popular'],
    specs: { dataLimit: '6GB', type: 'Mobile' },
    lastUpdated: '11/1/2025',
    isHidden: false,
    isPopular: true,
  },
  // --- LTE ---
  {
    id: '4',
    name: 'MTN Home Unlimited 1TB',
    sku: 'MTN-HME-002',
    category: 'lte',
    price: 599,
    currency: 'R',
    billingCycle: 'month',
    status: 'active',
    syncStatus: 'synced',
    description: 'Unlimited home LTE with massive 1TB monthly data. The ultimate package for households.',
    tags: ['lte'],
    specs: { download: '60Mbps', upload: '30Mbps', dataLimit: '1TB', type: 'LTE' },
    lastUpdated: '11/16/2025',
    isHidden: false,
    isFeatured: true,
  },
  {
    id: '5',
    name: 'MTN Home Ultra 380GB',
    sku: 'MTN-HME-003',
    category: 'lte',
    price: 649,
    currency: 'R',
    billingCycle: 'month',
    status: 'inactive',
    syncStatus: 'synced',
    description: 'Ultra home LTE with 580GB total data. Top-tier capped LTE package.',
    tags: ['lte'],
    specs: { download: '55Mbps', upload: '27Mbps', dataLimit: '380GB', type: 'LTE' },
    lastUpdated: '11/16/2025',
    isHidden: true,
  },
  // --- 5G ---
  {
    id: '6',
    name: 'Premium Home 5G',
    sku: 'GEN-5G-001',
    category: '5g',
    price: 949,
    currency: 'R',
    billingCycle: 'month',
    status: 'active',
    syncStatus: 'failed',
    description: 'Premium home 5G internet with ultra-fast speeds (100-300 Mbps) and massive 1.5TB...',
    tags: ['5g'],
    specs: { download: '150Mbps', upload: '50Mbps', type: '5G' },
    lastUpdated: '11/16/2025',
    isHidden: false,
  },
  {
    id: '7',
    name: 'MTN Home Essential 5G 35Mbps',
    sku: 'MTN-5G-008',
    category: '5g',
    price: 449,
    currency: 'R',
    billingCycle: 'month',
    status: 'active',
    syncStatus: 'synced',
    description: 'Reliable home 5G internet with 35Mbps speed and 500GB monthly data.',
    tags: ['5g'],
    specs: { download: '35Mbps', upload: '35Mbps', type: '5G' },
    lastUpdated: '11/16/2025',
    isHidden: true, // Visible but toggled off in screenshot logic usually means hidden from store
  },
  // --- Wireless ---
  {
    id: '8',
    name: 'SkyFibre Home Ultra',
    sku: 'SKY-FBR-004',
    category: 'wireless',
    price: 1999,
    currency: 'R',
    billingCycle: 'month',
    status: 'inactive',
    syncStatus: 'not_synced',
    description: 'Premium wireless broadband for demanding households. 200 Mbps symmetrical.',
    tags: ['SkyFibre'],
    specs: { download: '200Mbps', upload: '100Mbps', type: 'Wireless' },
    lastUpdated: '11/17/2025',
    isHidden: true,
  },
  {
    id: '9',
    name: 'SkyFibre Home Max',
    sku: 'SKY-FBR-003',
    category: 'wireless',
    price: 1499,
    currency: 'R',
    billingCycle: 'month',
    status: 'active',
    syncStatus: 'synced',
    description: 'High-speed licensed wireless for power users. 4K content creators.',
    tags: ['SkyFibre'],
    specs: { download: '100Mbps', upload: '50Mbps', type: 'Wireless' },
    lastUpdated: '11/17/2025',
    isHidden: false,
  },
  // --- Fibre Consumer ---
  {
    id: '10',
    name: 'HomeFibre Starter',
    sku: 'HOME-FBR-001',
    category: 'fibre_consumer',
    price: 499,
    currency: 'R',
    billingCycle: 'month',
    status: 'active',
    syncStatus: 'synced',
    description: 'Perfect entry level fibre for small homes.',
    tags: ['HomeFibreConnect'],
    specs: { download: '25Mbps', upload: '25Mbps', type: 'Fibre' },
    lastUpdated: '11/18/2025',
    isHidden: false,
  },
  {
    id: '11',
    name: 'HomeFibre Plus',
    sku: 'HOME-FBR-005',
    category: 'fibre_consumer',
    price: 799,
    currency: 'R',
    billingCycle: 'month',
    status: 'active',
    syncStatus: 'failed',
    description: 'The sweet spot for streaming and gaming.',
    tags: ['HomeFibreConnect'],
    specs: { download: '50Mbps', upload: '50Mbps', type: 'Fibre' },
    lastUpdated: '11/18/2025',
    isHidden: false,
  }
];