import type { Promotion } from './types/strapi'

// Mock promotions data matching Afrihost deals page design
export const mockPromotions: Promotion[] = [
  {
    id: 1,
    documentId: 'promo-1',
    title: '3GB FREE mobile data.',
    shortDescription: 'Sign up for AfrMobile today. More FREE calls than other networks.',
    description: '',
    category: 'mobile',
    badge: 'MOBILE',
    price: null,
    originalPrice: null,
    currency: 'ZAR',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#FF8C00',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/5cwtbmxt',
    featured: true,
    priority: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 2,
    documentId: 'promo-2',
    title: 'Save R5 000 on Fibre setup.',
    shortDescription: 'FREE installation. FREE activation. FREE WiFi router.',
    description: '',
    category: 'fibre',
    badge: 'FIBRE',
    price: 0,
    originalPrice: 5000,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#00BCD4',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/ue3k4w73',
    featured: true,
    priority: 95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 3,
    documentId: 'promo-3',
    title: 'Save R1 000 on Wireless hardware.',
    shortDescription: 'With selected Wireless SIM + Device packages.',
    description: '',
    category: 'wireless',
    badge: 'WIRELESS',
    price: 2499,
    originalPrice: 3499,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#9C27B0',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/yzj6r4vb',
    featured: true,
    priority: 90,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 4,
    documentId: 'promo-4',
    title: "Don't be left in the dark.",
    shortDescription: 'Mini DC Back-up UPS featuring 9 total of 8 separate battery power capacity.',
    description: '',
    category: 'devices',
    badge: 'DEVICES',
    price: 999,
    originalPrice: null,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#1F2937',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/3z2s4xvh',
    featured: true,
    priority: 85,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 5,
    documentId: 'promo-5',
    title: 'Monthly airtime and mobile data.',
    shortDescription: 'Everything you need on one SIM starting from only R35.00pm.',
    description: '',
    category: 'mobile',
    badge: 'MOBILE',
    price: 35,
    originalPrice: null,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#FF9800',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/2p86zmj6',
    featured: true,
    priority: 80,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 6,
    documentId: 'promo-6',
    title: 'FREE calls.',
    shortDescription: 'Sign up for AfrMobile today. More FREE calls than other networks.',
    description: '',
    category: 'voip',
    badge: 'VOIP',
    price: null,
    originalPrice: null,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#FF9800',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/y6pyp372',
    featured: true,
    priority: 75,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 7,
    documentId: 'promo-7',
    title: 'Fast WiFi to cover your whole house.',
    shortDescription: 'TP-Link Deco X50 Mesh WiFi system.',
    description: '',
    category: 'devices',
    badge: 'DEVICES',
    price: 3999,
    originalPrice: null,
    currency: 'R',
    ctaText: 'View Details',
    ctaLink: '/devices/tp-link-deco-x50',
    backgroundColor: '#FFFFFF',
    textColor: '#1F2937',
    imageUrl: 'https://design.canva.ai/aw5da76b',
    featured: true,
    priority: 70,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 8,
    documentId: 'promo-8',
    title: 'FREE WiFi router with Pure Fibre. +',
    shortDescription: 'Get a TP-Link EX1i with selected Pure packages!',
    description: '',
    category: 'fibre',
    badge: 'FIBRE',
    price: 0,
    originalPrice: 899,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#00BCD4',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/46zf5z74',
    featured: true,
    priority: 65,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 9,
    documentId: 'promo-9',
    title: 'Save R300 on a VoIP phone. + FREE delivery.',
    shortDescription: 'With any Call Centre or Device package.',
    description: '',
    category: 'voip',
    badge: 'VOIP',
    price: 1399,
    originalPrice: 1699,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#006064',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/2nye26hu',
    featured: true,
    priority: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 10,
    documentId: 'promo-10',
    title: 'Get a FREE WiFi router.',
    shortDescription: 'With selected Wireless SIM + Deco packages.',
    description: '',
    category: 'wireless',
    badge: 'WIRELESS',
    price: 0,
    originalPrice: 599,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#9C27B0',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/ycksmtxv',
    featured: true,
    priority: 55,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 11,
    documentId: 'promo-11',
    title: 'FREE domain for the 1st year.',
    shortDescription: '.co.za or .site or .online with any large or Wicked Shared hosting package.',
    description: '',
    category: 'hosting',
    badge: 'HOSTING',
    price: null,
    originalPrice: null,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#263238',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/2p8hrj44',
    featured: true,
    priority: 50,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 12,
    documentId: 'promo-12',
    title: 'Fast prepaid Fibre',
    shortDescription: 'R537 per month',
    description: '',
    category: 'fibre',
    badge: 'FREE',
    price: 537,
    originalPrice: null,
    currency: 'R',
    ctaText: 'Get this deal',
    ctaLink: '/order',
    backgroundColor: '#E91E63',
    textColor: '#FFFFFF',
    imageUrl: 'https://design.canva.ai/33dbrsdn',
    featured: true,
    priority: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
]