import type { CollectionConfig } from 'payload'

export const Media: CollectionConfig = {
  slug: 'media',
  access: {
    read: () => true,
  },
  upload: {
    staticDir: 'public/media',
    mimeTypes: ['image/*'],
    imageSizes: [
      {
        name: 'thumbnail',
        width: 400,
        height: 300,
        position: 'centre',
      },
      {
        name: 'hero',
        width: 1200,
        height: 630,
        position: 'centre',
      },
      {
        name: 'product',
        width: 800,
        height: 800,
        position: 'centre',
      },
    ],
    adminThumbnail: 'thumbnail',
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: true,
      label: 'Alt Text',
    },
    {
      name: 'credit',
      type: 'text',
      label: 'Credit / Source',
    },
    {
      name: 'aiGenerated',
      type: 'checkbox',
      label: 'AI Generated',
      defaultValue: false,
      admin: {
        description: 'Check if this image was generated by AI',
      },
    },
  ],
}
