/**
 * Spec Templates
 *
 * Template strings and helpers for generating Agent-OS specification files.
 *
 * @module lib/agents/pm/templates
 * @see agent-os/specs/20251129-agentic-ai-system/spec.md
 */

// ============================================================================
// README Template
// ============================================================================

/**
 * Generate README.md content for a spec.
 *
 * @param params - Template parameters
 * @returns README markdown content
 */
export function generateReadmeContent(params: {
  specId: string;
  title: string;
  description: string;
  totalPoints: number;
  priority: string;
  taskGroups: number;
  createdDate: string;
}): string {
  return `# ${params.title}

> **Spec ID**: \`${params.specId}\`

## Quick Links

- [📋 Full Specification](./spec.md)
- [📝 Task Breakdown](./tasks.md)
- [📊 Progress Tracking](./PROGRESS.md)

## Overview

${params.description}

## Summary

| Attribute | Value |
|-----------|-------|
| **Status** | Draft |
| **Priority** | ${params.priority} |
| **Story Points** | ${params.totalPoints} |
| **Task Groups** | ${params.taskGroups} |
| **Created** | ${params.createdDate} |

## Getting Started

1. Review the [Full Specification](./spec.md)
2. Check the [Task Breakdown](./tasks.md)
3. Update [Progress](./PROGRESS.md) as tasks complete

## Files

| File | Description |
|------|-------------|
| \`spec.md\` | Full technical specification |
| \`tasks.md\` | Detailed task breakdown |
| \`PROGRESS.md\` | Progress tracking |
| \`README.md\` | This file |

---

*Generated by PM Agent*
`;
}

// ============================================================================
// PROGRESS Template
// ============================================================================

/**
 * Generate initial PROGRESS.md content.
 *
 * @param params - Template parameters
 * @returns PROGRESS markdown content
 */
export function generateProgressContent(params: {
  specId: string;
  title: string;
  totalPoints: number;
  taskGroups: Array<{
    number: number;
    title: string;
    points: number;
    agent: string;
  }>;
}): string {
  const taskGroupRows = params.taskGroups
    .map(g => `| ${g.number} | ${g.title} | ${g.agent} | ${g.points} | 0 | 0% | NOT STARTED |`)
    .join('\n');

  return `# ${params.title} - Implementation Progress

## Overview

| Metric | Value |
|--------|-------|
| **Spec ID** | ${params.specId} |
| **Total Story Points** | ${params.totalPoints} |
| **Completed Story Points** | 0 |
| **Progress** | 0% |
| **Status** | NOT STARTED |
| **Last Updated** | ${new Date().toISOString().split('T')[0]} |

---

## Task Group Progress

| # | Task Group | Agent | Points | Completed | Progress | Status |
|---|------------|-------|--------|-----------|----------|--------|
${taskGroupRows}
| | **Total** | | **${params.totalPoints}** | **0** | **0%** | |

---

## Blockers

*None currently*

---

## Session Log

### ${new Date().toISOString().split('T')[0]}

**Session 1**
- Spec created
- Ready for implementation

---

## Cost Tracking

| Item | Cost |
|------|------|
| Development (Max subscription) | $0 |
| API credits used | $0 |
| **Total** | **$0** |

---

**Document Version**: 1.0
**Maintained By**: Development Team + Claude Code
`;
}

// ============================================================================
// Migration Template
// ============================================================================

/**
 * Generate SQL migration template.
 *
 * @param params - Template parameters
 * @returns SQL migration content
 */
export function generateMigrationTemplate(params: {
  tableName: string;
  description: string;
  columns?: Array<{
    name: string;
    type: string;
    nullable?: boolean;
    default?: string;
  }>;
}): string {
  const columnsSQL = params.columns
    ? params.columns
        .map(c => {
          let col = `  ${c.name} ${c.type}`;
          if (!c.nullable) col += ' NOT NULL';
          if (c.default) col += ` DEFAULT ${c.default}`;
          return col;
        })
        .join(',\n')
    : '  -- Add columns here';

  return `-- Migration: ${params.description}
-- Table: ${params.tableName}
-- Generated: ${new Date().toISOString()}

-- Create table
CREATE TABLE IF NOT EXISTS ${params.tableName} (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
${columnsSQL},
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE ${params.tableName} ENABLE ROW LEVEL SECURITY;

-- Create updated_at trigger
CREATE TRIGGER set_${params.tableName}_updated_at
  BEFORE UPDATE ON ${params.tableName}
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- RLS Policies
-- Allow users to read their own records
CREATE POLICY "Users can read own ${params.tableName}"
  ON ${params.tableName}
  FOR SELECT
  USING (auth.uid() = user_id);

-- Allow users to insert their own records
CREATE POLICY "Users can insert own ${params.tableName}"
  ON ${params.tableName}
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Allow users to update their own records
CREATE POLICY "Users can update own ${params.tableName}"
  ON ${params.tableName}
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Indexes
CREATE INDEX idx_${params.tableName}_user_id ON ${params.tableName}(user_id);
CREATE INDEX idx_${params.tableName}_created_at ON ${params.tableName}(created_at);
`;
}

// ============================================================================
// API Route Template
// ============================================================================

/**
 * Generate API route template.
 *
 * @param params - Template parameters
 * @returns TypeScript API route content
 */
export function generateAPIRouteTemplate(params: {
  path: string;
  methods: Array<'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'>;
  requiresAuth: boolean;
  description: string;
}): string {
  const imports = `import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
`;

  const authCheck = params.requiresAuth
    ? `
  // Authentication check
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
`
    : '';

  const methodHandlers = params.methods
    .map(method => {
      return `
/**
 * ${method} ${params.path}
 * ${params.description}
 */
export async function ${method}(
  request: NextRequest,
  context: { params: Promise<{ id?: string }> }
) {
  const supabase = await createClient();
${authCheck}
  try {
    // TODO: Implement ${method} handler
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('${method} ${params.path} error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}`;
    })
    .join('\n');

  return `${imports}${methodHandlers}
`;
}

// ============================================================================
// Component Template
// ============================================================================

/**
 * Generate React component template.
 *
 * @param params - Template parameters
 * @returns TypeScript React component content
 */
export function generateComponentTemplate(params: {
  name: string;
  description: string;
  hasProps: boolean;
  hasState: boolean;
}): string {
  const propsInterface = params.hasProps
    ? `
interface ${params.name}Props {
  // TODO: Define props
}
`
    : '';

  const stateHook = params.hasState
    ? `
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
`
    : '';

  const imports = ['React'];
  if (params.hasState) {
    imports.push('useState');
  }

  return `'use client';

import { ${imports.join(', ')} } from 'react';
${propsInterface}
/**
 * ${params.name}
 * ${params.description}
 */
export function ${params.name}(${params.hasProps ? `props: ${params.name}Props` : ''}) {
${stateHook}
  return (
    <div className="p-4">
      <h2 className="text-lg font-semibold">${params.name}</h2>
      {/* TODO: Implement component */}
    </div>
  );
}

export default ${params.name};
`;
}

// ============================================================================
// Service Template
// ============================================================================

/**
 * Generate service file template.
 *
 * @param params - Template parameters
 * @returns TypeScript service content
 */
export function generateServiceTemplate(params: {
  name: string;
  description: string;
  tableName?: string;
}): string {
  const tableImport = params.tableName
    ? `
import { createClient } from '@/lib/supabase/server';
`
    : '';

  const tableMethod = params.tableName
    ? `
  /**
   * Get all records from ${params.tableName}.
   */
  async getAll() {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('${params.tableName}')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      throw new Error(\`Failed to fetch ${params.tableName}: \${error.message}\`);
    }

    return data;
  }

  /**
   * Get a record by ID.
   */
  async getById(id: string) {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('${params.tableName}')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      throw new Error(\`Failed to fetch ${params.tableName}: \${error.message}\`);
    }

    return data;
  }
`
    : '';

  return `/**
 * ${params.name} Service
 * ${params.description}
 */
${tableImport}
class ${params.name}Service {
${tableMethod}
  // TODO: Add service methods
}

export const ${params.name.toLowerCase()}Service = new ${params.name}Service();
export default ${params.name.toLowerCase()}Service;
`;
}

// ============================================================================
// Exports
// ============================================================================

export const templates = {
  generateReadmeContent,
  generateProgressContent,
  generateMigrationTemplate,
  generateAPIRouteTemplate,
  generateComponentTemplate,
  generateServiceTemplate,
};

export default templates;
