/**
 * ZOHO Billing Invoice Sync Service
 *
 * Syncs CircleTel manual invoices to ZOHO Billing
 * IMPORTANT: Only syncs manual invoice types (installation, pro-rata, equipment, adjustment)
 * Recurring invoices are auto-generated by ZOHO from subscriptions
 *
 * Prerequisites:
 * - Customer must be synced to ZOHO first
 *
 * @see docs/architecture/ADMIN_SUPABASE_ZOHO_INTEGRATION.md
 */

import { createClient } from '@/lib/supabase/server';
import { ZohoBillingClient } from './billing-client';
import { syncCustomerToZohoBilling } from './customer-sync-service';
import { logZohoSync } from './sync-service';

export interface InvoiceSyncResult {
  success: boolean;
  zoho_invoice_id?: string;
  error?: string;
}

// Only these invoice types should be synced to ZOHO
// Recurring invoices are auto-generated by ZOHO from subscriptions
const SYNCABLE_INVOICE_TYPES = [
  'installation',
  'pro_rata',
  'equipment',
  'adjustment'
] as const;

/**
 * Sync a CircleTel invoice to ZOHO Billing
 *
 * @param invoice_id - CircleTel customer_invoices UUID
 * @returns Sync result with ZOHO invoice ID or error
 */
export async function syncInvoiceToZohoBilling(
  invoice_id: string
): Promise<InvoiceSyncResult> {
  const supabase = await createClient();

  try {
    console.log('[InvoiceSync] Starting sync for invoice:', invoice_id);

    // Update sync status to 'syncing'
    await supabase
      .from('customer_invoices')
      .update({ zoho_sync_status: 'syncing' })
      .eq('id', invoice_id);

    // Get invoice data from Supabase
    const { data: invoice, error: fetchError } = await supabase
      .from('customer_invoices')
      .select(`
        *,
        customer:customers(*)
      `)
      .eq('id', invoice_id)
      .single();

    if (fetchError || !invoice) {
      throw new Error(`Invoice not found: ${invoice_id}`);
    }

    // Check if invoice type is syncable
    if (!SYNCABLE_INVOICE_TYPES.includes(invoice.invoice_type as any)) {
      console.log('[InvoiceSync] Invoice type not syncable:', invoice.invoice_type);
      throw new Error(
        `Invoice type '${invoice.invoice_type}' should not be synced. Recurring invoices are auto-generated by ZOHO from subscriptions.`
      );
    }

    // Check if already synced
    if (invoice.zoho_billing_invoice_id) {
      console.log('[InvoiceSync] Invoice already synced:', invoice.zoho_billing_invoice_id);
      return {
        success: true,
        zoho_invoice_id: invoice.zoho_billing_invoice_id
      };
    }

    // Prerequisite: Ensure customer is synced to ZOHO
    console.log('[InvoiceSync] Checking customer sync status...');
    if (!invoice.customer?.zoho_billing_customer_id) {
      console.log('[InvoiceSync] Customer not synced, syncing now...');
      const customerSyncResult = await syncCustomerToZohoBilling(invoice.customer_id);
      if (!customerSyncResult.success || !customerSyncResult.zoho_customer_id) {
        throw new Error(`Failed to sync customer: ${customerSyncResult.error}`);
      }
      // Refresh customer data
      const { data: updatedCustomer } = await supabase
        .from('customers')
        .select('zoho_billing_customer_id')
        .eq('id', invoice.customer_id)
        .single();
      invoice.customer.zoho_billing_customer_id = updatedCustomer?.zoho_billing_customer_id;
    }

    console.log('[InvoiceSync] Prerequisites met:', {
      customer_id: invoice.customer.zoho_billing_customer_id
    });

    // Map line items from JSONB to ZOHO format
    const lineItems = Array.isArray(invoice.line_items)
      ? invoice.line_items.map((item: any) => ({
          item_id: item.item_id || undefined,
          name: item.name || item.description || 'Service',
          description: item.description || undefined,
          rate: parseFloat(item.price || item.rate || 0),
          quantity: parseInt(item.quantity || 1),
          // ZOHO calculates amount automatically: rate * quantity
        }))
      : [
          // Fallback if no line items: create single line from total
          {
            name: getInvoiceDescription(invoice.invoice_type),
            description: invoice.notes || undefined,
            rate: parseFloat(invoice.total_amount || 0),
            quantity: 1,
          }
        ];

    // Build ZOHO Billing invoice payload
    const zohoPayload = {
      customer_id: invoice.customer.zoho_billing_customer_id,
      invoice_number: invoice.invoice_number || undefined,
      date: invoice.invoice_date || new Date().toISOString().split('T')[0],
      due_date: invoice.due_date || undefined,
      payment_terms: invoice.payment_terms || 30, // Default 30 days
      payment_terms_label: invoice.payment_terms_label || 'Net 30',

      // Line items
      line_items: lineItems,

      // Notes and reference
      notes: invoice.notes || undefined,
      terms: invoice.terms || undefined,

      // Custom fields for CircleTel reference
      cf_circletel_invoice_id: invoice.id,
      cf_invoice_type: invoice.invoice_type,
      cf_service_id: invoice.service_id || undefined,
    };

    // Remove undefined fields
    Object.keys(zohoPayload).forEach(key => {
      if (zohoPayload[key as keyof typeof zohoPayload] === undefined) {
        delete zohoPayload[key as keyof typeof zohoPayload];
      }
    });

    console.log('[InvoiceSync] Creating ZOHO invoice:', {
      invoice_id,
      customer_email: invoice.customer.email,
      invoice_type: invoice.invoice_type,
      total_amount: invoice.total_amount
    });

    // Create invoice in ZOHO Billing
    const billingClient = new ZohoBillingClient();
    const zohoInvoice = await billingClient.createInvoice(zohoPayload);

    const zoho_invoice_id = zohoInvoice.invoice_id;

    console.log('[InvoiceSync] Successfully created ZOHO invoice:', {
      invoice_id: zoho_invoice_id,
      invoice_number: zohoInvoice.invoice_number,
      status: zohoInvoice.status,
      total: zohoInvoice.total
    });

    // Update invoice with ZOHO invoice ID
    await supabase
      .from('customer_invoices')
      .update({
        zoho_billing_invoice_id: zoho_invoice_id,
        zoho_sync_status: 'synced',
        zoho_last_synced_at: new Date().toISOString(),
        zoho_last_sync_error: null
      })
      .eq('id', invoice_id);

    // Log successful sync
    await logZohoSync({
      entity_type: 'invoice',
      entity_id: invoice_id,
      zoho_entity_type: 'Invoice',
      zoho_entity_id: zoho_invoice_id,
      status: 'success',
      attempt_number: 1,
      request_payload: zohoPayload,
      response_payload: zohoInvoice
    });

    return {
      success: true,
      zoho_invoice_id
    };

  } catch (error) {
    console.error('[InvoiceSync] Error syncing invoice:', error);

    const errorMessage = error instanceof Error ? error.message : 'Unknown error';

    // Update invoice with error status
    await supabase
      .from('customer_invoices')
      .update({
        zoho_sync_status: 'failed',
        zoho_last_sync_error: errorMessage
      })
      .eq('id', invoice_id);

    // Log failed sync
    await logZohoSync({
      entity_type: 'invoice',
      entity_id: invoice_id,
      zoho_entity_type: 'Invoice',
      zoho_entity_id: null,
      status: 'failed',
      attempt_number: 1,
      error_message: errorMessage,
      request_payload: null,
      response_payload: null
    });

    return {
      success: false,
      error: errorMessage
    };
  }
}

/**
 * Get sync status for an invoice
 *
 * @param invoice_id - CircleTel customer_invoices UUID
 * @returns Sync status details
 */
export async function getInvoiceSyncStatus(invoice_id: string) {
  const supabase = await createClient();

  const { data: invoice } = await supabase
    .from('customer_invoices')
    .select('zoho_billing_invoice_id, zoho_sync_status, zoho_last_synced_at, zoho_last_sync_error')
    .eq('id', invoice_id)
    .single();

  if (!invoice) {
    return null;
  }

  return {
    synced: !!invoice.zoho_billing_invoice_id,
    zoho_invoice_id: invoice.zoho_billing_invoice_id,
    sync_status: invoice.zoho_sync_status,
    last_synced_at: invoice.zoho_last_synced_at,
    error: invoice.zoho_last_sync_error
  };
}

/**
 * Find manual invoices that need syncing
 *
 * @param limit - Maximum number of invoices to return
 * @returns Array of invoice IDs needing sync
 */
export async function findInvoicesNeedingSync(limit: number = 100): Promise<string[]> {
  const supabase = await createClient();

  const { data: invoices } = await supabase
    .from('customer_invoices')
    .select('id')
    .in('invoice_type', SYNCABLE_INVOICE_TYPES)
    .is('zoho_billing_invoice_id', null)
    .eq('zoho_sync_status', 'pending')
    .limit(limit);

  return invoices?.map(i => i.id) || [];
}

/**
 * Helper: Get human-readable description for invoice type
 */
function getInvoiceDescription(invoice_type: string): string {
  const descriptions: Record<string, string> = {
    installation: 'Installation Fee',
    pro_rata: 'Pro-Rata Service Fee',
    equipment: 'Equipment Charge',
    adjustment: 'Account Adjustment'
  };
  return descriptions[invoice_type] || 'Service Charge';
}
