# Optimized CI workflow - most validation now happens locally via pre-commit hooks
# This runs lightweight checks since pre-commit validation ensures code quality
#
# Optimization Strategy:
# - Pre-commit hooks catch 99% of issues locally (never reach CI)
# - validate & build: Always run in parallel (~2-3 minutes total)
# - test: Only runs on PRs or when commit message contains [run-tests]
# - Playwright browsers: Cached to avoid re-downloading (saves ~2-3 minutes)
# - Dependencies: Cached and installed with --prefer-offline --no-audit

name: CI

on:
  push:
    branches: [ main, master, 'mtn-dfa-coverage-integration' ]
  pull_request:
    branches: [ main, master ]

# Optimize for speed - run jobs in parallel where possible
jobs:
  # Fast validation job - runs first as a gate
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Type check
        run: npm run type-check

      - name: Lint check
        run: npm run lint

  # Build job - runs in parallel with validate
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build production
        run: npm run build

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
          retention-days: 7

  # Decision job - shows whether tests will run
  test-decision:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check test conditions
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Contains [run-tests]: ${{ contains(github.event.head_commit.message, '[run-tests]') }}"
          echo "Is PR: ${{ github.event_name == 'pull_request' }}"
          if [[ "${{ github.event_name }}" == "pull_request" || "${{ contains(github.event.head_commit.message, '[run-tests]') }}" == "true" ]]; then
            echo "✅ Tests WILL run"
          else
            echo "⏭️ Tests SKIPPED (use [run-tests] in commit message to run tests)"
          fi

  # Test job - only runs when explicitly needed to save CI time
  test:
    runs-on: ubuntu-latest
    needs: validate
    timeout-minutes: 15
    # Only run on pull requests or when commit message explicitly contains [run-tests]
    # This should skip tests on regular commits to save CI time and resources
    if: ${{ github.event_name == 'pull_request' || contains(github.event.head_commit.message, '[run-tests]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Run Tests
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 3
