name: Refresh MTN Session

# Run every 50 minutes to keep session alive
on:
  schedule:
    # Runs at minute 0 and 50 of every hour (every 50 minutes)
    - cron: '0,50 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  refresh-session:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Authenticate with MTN SSO
        env:
          MTN_USERNAME: ${{ secrets.MTN_USERNAME }}
          MTN_PASSWORD: ${{ secrets.MTN_PASSWORD }}
        run: |
          echo "🔐 Starting MTN SSO authentication..."
          npx tsx scripts/test-mtn-sso-auth.ts --headless

          if [ -f .cache/mtn-session.json ]; then
            echo "✅ Session created successfully"
          else
            echo "❌ Session creation failed"
            exit 1
          fi

      - name: Export session to base64
        id: export_session
        run: |
          echo "📤 Exporting session..."
          SESSION_BASE64=$(npx tsx scripts/export-session-env.ts --output-only)
          echo "SESSION_BASE64=$SESSION_BASE64" >> $GITHUB_OUTPUT
          echo "✅ Session exported"

      - name: Update Vercel environment variables
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          SESSION_BASE64: ${{ steps.export_session.outputs.SESSION_BASE64 }}
        run: |
          echo "🔄 Updating Vercel environment variable..."

          # Update production environment
          curl -X PATCH \
            "https://api.vercel.com/v10/projects/$VERCEL_PROJECT_ID/env/MTN_SESSION" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"value\": \"$SESSION_BASE64\",
              \"target\": [\"production\", \"preview\", \"development\"]
            }"

          echo "✅ Environment variable updated"

      - name: Trigger Vercel redeployment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "🚀 Triggering Vercel redeployment..."

          curl -X POST \
            "https://api.vercel.com/v13/deployments" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"name\": \"$VERCEL_PROJECT_ID\",
              \"target\": \"production\"
            }"

          echo "✅ Redeployment triggered"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Session refresh failed!"
          echo "Please manually refresh the session:"
          echo "1. Run: npx tsx scripts/test-mtn-sso-auth.ts --manual"
          echo "2. Run: npx tsx scripts/export-session-env.ts"
          echo "3. Update MTN_SESSION in Vercel dashboard"
